[package]
edition = "2021"
name = "lox-interpreter"
version = "0.1.0"

[[bin]]
name = "rlox"
path = "src/main.rs"

[lib]
name = "lox_interpreter"
path = "src/lib.rs"

[dev-dependencies]
assert_cmd = "2.0.4"
